import {
  BadgeDollarSign,
  Bell,
  Book,
  Bot,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Car,
  ClipboardList,
  Cloud,
  Code2,
  Cpu,
  CreditCard,
  Database,
  FileText,
  Film,
  Folder,
  FolderLock,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  Home,
  Image,
  Key,
  Landmark,
  Laptop,
  Mail,
  MapPinned,
  MessageCircle,
  Monitor,
  Music,
  Package,
  Phone,
  Plane,
  Receipt,
  Router,
  Server,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  Store,
  Terminal,
  Tv,
  User,
  Users,
  Wallet,
  Wifi,
  Wrench,
} from 'lucide-react';

export const COLLECTION_ICONS = [
  { name: 'Personal', icon: User, id: 'personal' },
  { name: 'Work', icon: Briefcase, id: 'work' },
  { name: 'General', icon: Folder, id: 'general' },
  { name: 'Favourite', icon: Star, id: 'favourite' },
  { name: 'Security', icon: ShieldCheck, id: 'security' },
  { name: 'Keys', icon: Key, id: 'keys' },

  { name: 'Email', icon: Mail, id: 'email' },
  { name: 'Social', icon: Users, id: 'social' },
  { name: 'Chats', icon: MessageCircle, id: 'chats' },
  { name: 'Websites', icon: Globe, id: 'websites' },
  { name: 'Cloud', icon: Cloud, id: 'cloud' },

  { name: 'Shopping', icon: ShoppingCart, id: 'shopping' },
  { name: 'Finance', icon: Wallet, id: 'finance' },
  { name: 'Payments', icon: CreditCard, id: 'payments' },
  { name: 'Banking', icon: Landmark, id: 'banking' },
  { name: 'Bills', icon: Receipt, id: 'bills' },
  { name: 'Subscriptions', icon: BadgeDollarSign, id: 'subscriptions' },

  { name: 'Devices', icon: Smartphone, id: 'devices' },
  { name: 'Laptop', icon: Laptop, id: 'laptop' },
  { name: 'Desktop', icon: Monitor, id: 'desktop' },
  { name: 'Storage', icon: HardDrive, id: 'storage' },
  { name: 'Network', icon: Wifi, id: 'network' },
  { name: 'Router', icon: Router, id: 'router' },

  { name: 'Travel', icon: Plane, id: 'travel' },
  { name: 'Home', icon: Home, id: 'home' },
  { name: 'Health', icon: Stethoscope, id: 'health' },
  { name: 'Education', icon: GraduationCap, id: 'education' },

  { name: 'Development', icon: Code2, id: 'development' },
  { name: 'Servers', icon: Server, id: 'servers' },
  { name: 'Database', icon: Database, id: 'database' },
  { name: 'Terminal', icon: Terminal, id: 'terminal' },
  { name: 'AI Tools', icon: Bot, id: 'ai_tools' },

  { name: 'Documents', icon: FileText, id: 'documents' },
  { name: 'Notes', icon: ClipboardList, id: 'notes' },
  { name: 'Secure Folder', icon: FolderLock, id: 'secure_folder' },

  { name: 'Gaming', icon: Gamepad2, id: 'gaming' },
  { name: 'Entertainment', icon: Tv, id: 'entertainment' },
  { name: 'Music', icon: Music, id: 'music' },
  { name: 'Photos', icon: Camera, id: 'photos' },
  { name: 'Film', icon: Film, id: 'film' },
  { name: 'Books', icon: Book, id: 'books' },
  { name: 'Calendar', icon: Calendar, id: 'calendar' },
  { name: 'Gift', icon: Gift, id: 'gift' },
  { name: 'Like', icon: Heart, id: 'like' },

  { name: 'Business', icon: Building2, id: 'business' },
  { name: 'Transport', icon: Car, id: 'transport' },
  { name: 'Phone', icon: Phone, id: 'phone' },
  { name: 'Stores', icon: Store, id: 'stores' },
  { name: 'Packages', icon: Package, id: 'packages' },
  { name: 'Places', icon: MapPinned, id: 'places' },
  { name: 'Audio', icon: Headphones, id: 'audio' },
  { name: 'Gallery', icon: Image, id: 'gallery' },
  { name: 'Tools', icon: Wrench, id: 'tools' },
  { name: 'Admin', icon: Hammer, id: 'admin' },
  { name: 'Alerts', icon: Bell, id: 'alerts' },
  { name: 'Hardware', icon: Cpu, id: 'hardware' },
];
